---
- name: reload systemd
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == "systemd"

- name: stop httpd
  service:
    name: '{{ item }}'
    state: stopped
  with_items: '{{ httpd_service_names }}'

- name: start httpd
  service:
    name: '{{ item }}'
    state: started
  with_items: '{{ httpd_service_names }}'

- name: reload httpd
  service:
    name: '{{ item }}'
    state: reloaded
  with_items: '{{ httpd_service_names }}'

- name: restart httpd
  service:
    name: '{{ item }}'
    state: restarted
  with_items: '{{ httpd_service_names }}'
