---
- name: '{{ httpd_config_file }}'
  template:
    src: '{{ httpd_config_file_template }}'
    dest: '{{ httpd_config_file }}'
    owner: root
    group: root
    mode: '0644'
  when: httpd_use_templatefile
  notify:
  - restart httpd
